### ISSUE TITLE
Vault & Restaking: Optimize account loading

### ISSUE THREAD

**Issue by buffalu** [jito-foundation/restaking#6]
Boxes are used (yuk). Try zero-copy or design better account loading so the program is more efficient

**Comment by aoikurokawa** [comment]
Hi! @buffalu 
The issue is that the current implementation uses Box, which is not efficient:

```rust
pub struct SanitizedConfig<'a, 'info> {
    account: &'a AccountInfo<'info>,
    config: Box<Config>,
}
```

To address this, implementing Pod and Zeroable from bytemuck for the `Config` struct for example:

```rust
#[derive(Debug, Copy, BorshSerialize, BorshDeserialize, Clone)]
pub struct Config {
    ...
}

unsafe impl Pod for Config {}
unsafe impl Zeroable for Config {}
```

This would allow us to remove the Box, I guess:

```rust
pub struct SanitizedConfig<'a, 'info> {
    account: &'a AccountInfo<'info>,
    config: Config,
}
```

Would this be the right way to solve the issue and improve efficiency?
